### PR TITLE
user-service crud

### PR DESCRIPTION
**Pull request by decipherDev**

### CODE REVIEW

**Comment by spallya** [comment]
add swagger documentation for controller and dtos

**Comment by spallya** [comment]
create some custom exceptions like bookNotFound, userNotFound etc to return some valuable feedback to the client

**Comment by spallya** [comment]
Create a controller advice for handling exceptions at a single place

**Comment by spallya** [comment]
Write integrations tests and unit tests for each layer controller, service and repository

**Comment by decipherDev** [comment]
> add swagger documentation for controller and dtos

I have done this under week-2 as soon as this PR is merged I'll raise separate PR for week-2 which has swagger and flyway integration.

**Comment by decipherDev** [comment]
@spallya I have addressed all the review comments. I have not unit tested the repository layer extensively as there is no custom code for it. Please review.

**Review by spallya — APPROVED** [review]

**Pull request merged**
